#!/usr/bin/sh

export DISPLAY=:0
export XAUTHORITY=/home/srsantos/.Xauthority
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

state=$8

if [ "$state" = "NOCARD" ]; then
  /usr/bin/xset dpms force off && /usr/bin/gpgconf --kill gpg-agent
fi
