#!/usr/bin/bash

hc() {
    herbstclient "$@"
}

hc pad 0 18 0 0 0

hc emit_hook reload

# autostart programs
/usr/bin/xcalib -d :0 /home/srsantos/.color/icc/lp125wh2-slb3.icc &
/usr/bin/setroot -z /home/srsantos/.i3/wallpapers/dark-metal-grids/dark-metal-grid-2.png &
/usr/bin/xss-lock -- i3lock -f -i /home/srsantos/.i3/wallpapers/metal_grid_w_arch_lockscreen.png &
/usr/bin/unclutter --timeout 10 --jitter 50 --exclude-root --ignore-scrolling --fork

if hc silent new_attr bool my_not_first_autostart ; then
    /usr/bin/xvisbell &
    /usr/bin/rm -f /tmp/touchpad_toggled.* &>/dev/null &
    /usr/local/bin/touchpad_toggle.sh &
    /usr/local/bin/toggle_xautolock.sh
fi

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-e close_or_remove

hc keybind $Mod-Return spawn termite -c /home/srsantos/.config/termite/config_herbstluftwm
hc keybind $Mod-d spawn rofi -show run
hc keybind $Mod-Shift-n spawn /usr/bin/networkmanager_dmenu
hc keybind $Mod-b spawn /usr/bin/luakit

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
#hc keybind $Mod-h     focus left
#hc keybind $Mod-j     focus down
#hc keybind $Mod-k     focus up
#hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
#hc keybind $Mod-Shift-h     shift left
#hc keybind $Mod-Shift-j     shift down
#hc keybind $Mod-Shift-k     shift up
#hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Shift-h       split   bottom  0.5
hc keybind $Mod-Shift-v       split   right   0.5

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
#hc keybind $Mod-Control-h       resize left +$resizestep
#hc keybind $Mod-Control-j       resize down +$resizestep
#hc keybind $Mod-Control-k       resize up +$resizestep
#hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
        hc keybind "$Mod-Control-$key" chain , move_index "$i" , use_index "$i"
    fi
done

#hc load 1     '(clients max:0)'

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s cycle_layout 1
hc keybind $Mod-space floating toggle
#hc keybind $Mod-Shift-space floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# keybindings for locking screen
#hc keybind $Mod-Control-l spawn /usr/local/bin/toggle_xautolock.sh
#hc keybind $Mod-Shift-Control-l spawn /usr/bin/xset dpms force off

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-x jumpto urgent
hc keybind $Mod-z use_previous

# keybindings for audio hotkeys
#hc keybind XF86AudioRaiseVolume spawn /usr/bin/amixer -q sset Master 5%+ unmute
#hc keybind XF86AudioLowerVolume spawn /usr/bin/amixer -q sset Master 5%- unmute
#hc keybind XF86AudioMute spawn /usr/bin/amixer -q sset Master toggle
hc keybind XF86AudioRaiseVolume spawn /usr/bin/pulseaudio-ctl up
hc keybind XF86AudioLowerVolume spawn /usr/bin/pulseaudio-ctl down
hc keybind XF86AudioMute spawn /usr/bin/pulseaudio-ctl mute
hc keybind XF86AudioMicMute spawn /usr/bin/pulseaudio-ctl mute-input

# keybindings for Pandora hotkeys
hc keybind XF86AudioPlay spawn /usr/local/bin/control-pianobar.sh p
hc keybind XF86AudioNext spawn /usr/local/bin/control-pianobar.sh next
hc keybind XF86AudioPrev spawn /usr/local/bin/control-pianobar.sh switchstation

# keybindings for brightness hotkeys
hc keybind XF86MonBrightnessUp spawn /usr/bin/light -A 10
hc keybind XF86MonBrightnessDown spawn /usr/bin/light -U 10

# keybindings for various system hotkeys
hc keybind XF86Sleep spawn /usr/bin/systemctl suspend
hc keybind XF86ScreenSaver spawn /usr/bin/xset dpms force off
hc keybind XF86Launch1 spawn /usr/local/bin/rofi_i3exit.sh
hc keybind Print spawn /usr/bin/scrot '%Y-%m-%d-%T_$wx$h_scrot.png' -e 'mv $f ~/Pictures/screenshots/'

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#00CCCC'
hc set frame_border_normal_color '#396EB4'
hc set frame_bg_normal_color '#396EB4'
hc set frame_bg_active_color '#396EB4'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 1
hc set frame_gap 4

hc attr theme.active.color '#396EB4'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#EF2929'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#396EB4' ##'#007F7F'
hc attr theme.active.outer_color '#396EB4'
hc attr theme.background_color '#141414'

hc set window_gap 4
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class=Luakit tag=8 focus=on switchtag=on
hc rule class=mutt tag=9 focus=on switchtag=on
hc rule class=Pinentry-gtk-2 pseudotile=on focus=on switchtag=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off focus=on
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off focus=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# start tint2 and kill/restart on hlwm reload
#{
#pids=( )
# start the panel and remember its pid
#tint2 &
#pids+=( $! )
# wait until the panel should be stopped
#herbstclient -w '(quit_panel|reload)'
# stop all started panels
#kill ${pids[@]}
#} &

# start i3status and kill/restart on hlwm reload
#{
#pids=( )
# start the panel and remember its pid
#i3status -c ~/.config/i3status/dzen2/config | dzen2 -fn "PragmataPro:size=8" &
#pids+=( $! )
# wait until the panel should be stopped
#herbstclient -w '(quit_panel|reload)'
# stop all started panels
#kill ${pids[@]}
#} &


# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# start the panel
panel=/home/srsantos/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
