#!/usr/bin/env bash

hc() {
   herbstclient "$@"
}

hc pad 0 18 0 0 0

hc emit_hook reload

# autostart programs
/usr/bin/xcalib -d :0 /home/srsantos/.color/icc/Lenovo_Twist_s230u_IPS.icm &
/usr/bin/setroot -z /home/srsantos/.i3/wallpapers/dark-metal-grids/dark-metal-grid-8.png &

if hc silent new_attr bool my_not_first_autostart ; then
    /usr/bin/xvisbell &
#    /usr/bin/compton --vsync opengl --paint-on-overlay &>/dev/null &
    /usr/bin/compton --config /home/srsantos/.config/compton/compton_simple.conf &>/dev/null &
    /usr/local/bin/touchpad_toggle.sh &
    /usr/local/bin/toggle_xautolock.sh &
    /usr/bin/unclutter --timeout 10 --jitter 50 --exclude-root --ignore-scrolling --fork &
    /usr/bin/opensc-notify &
fi

# remove all existing keybindings
hc keyunbind --all

# keybindings
# Use the super key as the main modifier
Mod=Mod4
hc keybind $Mod-Return spawn termite -c /home/srsantos/.config/termite/config_herbstluftwm

# Reload and close/remove frames
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-e close_or_remove

# Various rofi menus and launchers
hc keybind $Mod-d spawn rofi -show run
hc keybind $Mod-Shift-p spawn rofi-pass
hc keybind $Mod-Shift-n spawn networkmanager_dmenu
hc keybind $Mod-Shift-w spawn weather_report_long.shw
hc keybind $Mod-Shift-s spawn scratchpad.sh

# Launch luakit
hc keybind $Mod-b spawn /usr/local/bin/luakit_light.sh

# Toggle panel
hc keybind $Mod-Shift-b spawn herbstclient emit_hook togglehidepanel

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Shift-h       split   bottom  0.5
hc keybind $Mod-Shift-v       split   right   0.5

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# set default layout
hc set default_frame_layout 1

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
        hc keybind "$Mod-Control-$key" spawn bash -c "herbstclient move_index "$i" ; herbstclient use_index "$i""
    fi
done

# load mutt and gtk-pinentry as max/fullscreen
hc load 9     '(clients max:0)'

# cycle through tags
#hc keybind $Mod-period use_index +1 --skip-visible
#hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-comma spawn /home/srsantos/.dotfiles/herbstluftwm/.config/herbstluftwm/tagswitch prev
hc keybind $Mod-period spawn /home/srsantos/.dotfiles/herbstluftwm/.config/herbstluftwm/tagswitch next

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s cycle_layout 1
hc keybind $Mod-space floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-x jumpto urgent
hc keybind $Mod-z use_previous

# keybindings for audio hotkeys
hc keybind XF86AudioRaiseVolume spawn /usr/bin/pulseaudio-ctl up
hc keybind XF86AudioLowerVolume spawn /usr/bin/pulseaudio-ctl down
hc keybind XF86AudioMute spawn /usr/bin/pulseaudio-ctl mute
hc keybind XF86AudioMicMute spawn /usr/bin/pulseaudio-ctl mute-input

# keybindings for Pandora hotkeys
hc keybind XF86AudioPlay spawn /usr/local/bin/control-pianobar.sh p
hc keybind XF86AudioNext spawn /usr/local/bin/control-pianobar.sh next
hc keybind XF86AudioPrev spawn /usr/local/bin/control-pianobar.sh switchstation

# keybindings for brightness hotkeys
hc keybind XF86MonBrightnessUp spawn /usr/bin/xbacklight -inc 10
hc keybind XF86MonBrightnessDown spawn /usr/bin/xbacklight -dec 10

# keybindings for various system hotkeys
hc keybind XF86Sleep spawn /usr/bin/systemctl suspend
hc keybind XF86ScreenSaver spawn /usr/bin/xset dpms force off
hc keybind XF86Launch1 spawn /usr/local/bin/rofi_i3exit.sh
hc keybind Print spawn /usr/bin/scrot '%Y-%m-%d-%T_$wx$h_scrot.png' -e 'mv $f ~/Pictures/screenshots/'

# theme (original blue = #396EB_4
hc set always_show_frame 1
hc set frame_border_active_color '#00CCCC'
hc set frame_border_normal_color '#454749'
hc set frame_bg_normal_color '#454749'
hc set frame_bg_active_color '#454749'
hc set frame_border_width 2
hc set frame_bg_transparent 1
hc set frame_transparent_width 1
hc set frame_gap 1
hc set frame_padding 0
hc set mouse_recenter_gap 0
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 1
hc set window_gap 2

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.active.color '#454749'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#EF2929'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#454749' ##'#007F7F'
hc attr theme.active.outer_color '#454749'
hc attr theme.background_color '#141414'

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class=mutt tag=9 focus=on switchtag=on
hc rule class=Pinentry-gtk-2 pseudotile=on focus=on switchtag=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off focus=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off focus=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# start and fork luakit & icecat "urgent on open"
/usr/local/bin/luakit_urgent_open.sh &
/usr/local/bin/chromium_urgent_open.sh &

# start the panel
panel=/home/srsantos/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
